language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-003131
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./dockerTask.sh
script:
  - ./build.sh
  - ./dockerTask.sh build release